using System;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using Newtonsoft.Json;
using Spine.Unity;
using UnityEditor;
using UnityEngine;

public class Utils
{

    private const string UNITY_AUTOGENERATED_CLONE_NAME = "(clone) ";
    public static T ParseEnum<T>(string value, bool ignoreCase = true)
    {
        return (T)Enum.Parse(typeof(T), value, ignoreCase);
    }

    public static T GetOrAddComponent<T>(GameObject go) where T : UnityEngine.Component
    {
        T component = go.GetComponent<T>();
        if (component == null)
            component = go.AddComponent<T>();
        return component;
    }
    
    public static string EraseUnityAutoGeneratedCloneName(string name)
    {
        int index = name.IndexOf(UNITY_AUTOGENERATED_CLONE_NAME);
        if (index > 0)
            name = name.Substring(0, index);
        return name;
            
    }

    public static T DeepCopy<T>(T source)
    {
        var serialized = JsonConvert.SerializeObject(source);
        return JsonConvert.DeserializeObject<T>(serialized);
    }
    
    public static double DotProduct(Vector2 v1, Vector2 v2)
    {
        return v1.x * v2.x + v1.y * v2.y;
    }

    public static Vector3 GetUIWorldPosition(RectTransform rectTransform)
    {
        Vector3 screenPosition = RectTransformUtility.WorldToScreenPoint(Camera.main, rectTransform.position);
        // 화면 좌표를 월드 좌표로 변환
        RectTransformUtility.ScreenPointToWorldPointInRectangle(rectTransform, screenPosition, Camera.main, out var worldPosition);
        return worldPosition;

    }

    public static void CharacterSkeletonInit(SkeletonGraphic skeletonGraphic,string characterPackName)
    {
        skeletonGraphic.skeletonDataAsset = ResourceManager.Instance.Load<SkeletonDataAsset>($"{characterPackName}_{ELabelNames.SkeletonData}");
        skeletonGraphic.material = ResourceManager.Instance.Load<Material>($"{characterPackName}_{ELabelNames.UIMaterial}");
        string skinName = skeletonGraphic.skeletonDataAsset.name;
        skeletonGraphic.initialSkinName = skinName.Substring(0, skinName.LastIndexOf('_'));
        skeletonGraphic.Initialize(true);
    }

    public static Sprite GetSpriteFromAnimationClip(AnimationClip clip, float time)
    {
        // Get all curves in the animation clip
        EditorCurveBinding[] bindings = AnimationUtility.GetObjectReferenceCurveBindings(clip);
        
        foreach (var binding in bindings)
        {
            if (binding.propertyName.Contains("m_Sprite"))
            {
                ObjectReferenceKeyframe[] keyframes = AnimationUtility.GetObjectReferenceCurve(clip, binding);
                
                // Find the keyframe at the specified time (or closest to it)
                foreach (var keyframe in keyframes)
                {
                    if (Mathf.Approximately(keyframe.time, time))
                    {
                        return keyframe.value as Sprite;
                    }
                }
            }
        }

        return null;
    }
    

    public class ReadonlyNumber<T>
    {
        private readonly T _value;
        public T Value => _value;

        public ReadonlyNumber(T value)
        {
            _value = value;
        }
        
    }
}