title: "[Idea] "
body:
  - type: markdown
    attributes:
      value: |
        ##💡아이디어 기획서
        > <span style="color:green"> Tip : <span style="color:black"> **해당 아이디어 항목에서는 어떤 것을 기획할 것인지 추상적으로 적어둡니다.**
  - type: textarea
    id: reference
    attributes:
      label: 레퍼런스 설명 및 소개
      description: "레퍼런스가 되는 게임의 이미지를 첨부하고, 어떤 시스템의 어떤 기능을 레퍼런스로 하는지 설명해야 합니다."
    validations:
      required: true
  - type: textarea
    id: difference
    attributes:
      label: 아이디어 정리
      description: "레퍼런스를 참고 또는 창작할 아이디어를 순차적으로 정리합니다."
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 연계되는 티켓
      description: "연계되는 다른 티켓이 있다면 넣어주세요"
      placeholder: "#1"
    validations:
      required: false
