name: 코드수정 템플릿
description: 개발자 전용 버그나 코드 리팩토링 관련 수정 관련 템플릿
title: "[수정]"

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: 작업 내역 설명
      description: 작업한 내용을 설명하세요
      placeholder: ex. 플레이어 이동 버그 고침
    validations:
      required: true
  - type: textarea
    id: help-contents
    attributes:
      label: 리뷰요청 사항
      description: 특별히 리뷰를 요청할 사항이 있다면 적어주세요
      placeholder: ex. 해당 함수 이름을 추천
    validations:
      required: true
  - type: input
    id: prepare-issue
    attributes:
      label: Report Issue(Optional)
      description: 해당 Report된 Bug Issue를 등록해주세요
      placeholder: "ex. #14"
    validations:
      required: false
